// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbK2xK8sYAgwa1LAWZiA7HBYKz0ZzoCc',
    appId: '1:883505518638:web:8640f0f7de8e53d092a7bf',
    messagingSenderId: '883505518638',
    projectId: 'devlabib',
    authDomain: 'devlabib.firebaseapp.com',
    storageBucket: 'devlabib.firebasestorage.app',
    measurementId: 'G-1ZH2DNP8L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SAw3rTE7vBu7IwPLuhOpbf5WvluPZBI',
    appId: '1:883505518638:android:99718867c0d6271e92a7bf',
    messagingSenderId: '883505518638',
    projectId: 'devlabib',
    storageBucket: 'devlabib.firebasestorage.app',
  );
}
